// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearConfig():Promise<void>;

export function GetConfig():Promise<main.DesktopConfig>;

export function GetConfigPath():Promise<string>;

export function HasConfig():Promise<boolean>;

export function SaveConfig(arg1:string,arg2:string):Promise<void>;
