// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearConfig() {
  return window['go']['main']['App']['ClearConfig']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function HasConfig() {
  return window['go']['main']['App']['HasConfig']();
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}
